
    -- This schema is copied from spring site and is exact same as spring use
    -- for default schema
    create table users(
      username varchar_ignorecase(50) not null primary key,
      password varchar_ignorecase(50) not null,
      enabled boolean not null
    );

  create table authorities (
      id bigint generated by default as identity(start with 1) primary key,
      username varchar_ignorecase(50) not null,
      authority varchar_ignorecase(50) not null,
      constraint fk_authorities_users foreign key(username) references users(username)
  );

  create unique index ix_auth_username on authorities (username, authority);